package chapter02.exceptions

fun erroneousCode() {
    // 예외를 보려면 다음 줄의 주석을 해제
    // val i = "1$".toInt()
}

fun main() {
    erroneousCode()
}